name: Test Print Workflow
on:
  push:
    branches:
      - test_1

jobs:
  print_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print messages
        run: 
          echo "Impresión 1"
          echo "Impresión 2"
          echo "Impresión 3"